services:
  db:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: meu_banco_de_dados
    ports:
      - "3307:3306"  # <--- Mudança aqui: Sua máquina acessa pela 3307
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: